version: '3'
services:
  portfolio:
    build:
      context: ../
    ports:
      - 8080:8080
    tty: true
    container_name: portfolio-dev-container
    restart: on-failure
    network_mode: "bridge"