service: default
runtime: nodejs10
instance_class: F2
default_expiration: 1d 12h
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 12
  min_instances: 0
  min_pending_latency: 30ms
  max_pending_latency: 50ms