apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: portfolio-dev
    context: ../
    docker:
      dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
    - deploy-dev.yaml
